#!/bin/bash
# Quick test script for the Ashby application form

echo "=========================================="
echo "Testing Job Autofill with Real Application"
echo "=========================================="
echo ""
echo "Application Details:"
echo "  Company: adaption (Adaptable Labs)"
echo "  Position: Machine Learning Engineer (Applied ML)"
echo "  Platform: Ashby (React-based form)"
echo ""
echo "Test File Location:"
echo "  $(pwd)/example/application.html"
echo ""
echo "Browser URL:"
echo "  file://$(pwd)/example/application.html"
echo ""
echo "=========================================="
echo "Manual Testing Steps:"
echo "=========================================="
echo ""
echo "1. OPEN IN CHROME:"
echo "   - Copy the URL above"
echo "   - Paste into Chrome address bar"
echo "   - Press Enter"
echo ""
echo "2. WAIT FOR FORM TO LOAD:"
echo "   - The page uses React and loads from CDN"
echo "   - Wait 2-3 seconds for form to fully render"
echo "   - You should see the application form with fields"
echo ""
echo "3. OPEN EXTENSION POPUP:"
echo "   - Click the Job Autofill icon in Chrome toolbar"
echo "   - Check the status message"
echo ""
echo "4. EXPECTED RESULTS:"
echo "   ✓ Should show: 'Found X fillable fields'"
echo "   ✓ May show: '(in iframe)' if form is in iframe"
echo "   ✓ Fill Form button should be enabled"
echo ""
echo "5. TEST FORM FILLING:"
echo "   - Click 'Fill Form' button"
echo "   - Watch which fields get filled"
echo "   - Check console for any errors (F12)"
echo ""
echo "6. EXPECTED FIELDS TO FILL:"
echo "   ✓ Name"
echo "   ✓ Email"
echo "   ✓ Phone Number"
echo "   ✓ LinkedIn"
echo "   ⚠ Location (may be partial)"
echo "   ⚠ Personal Website"
echo "   ⚠ Github (if pattern exists)"
echo "   ⚠ Twitter/X (if pattern exists)"
echo ""
echo "7. FIELDS THAT WON'T FILL (EXPECTED):"
echo "   ✗ Resume (file upload)"
echo "   ✗ Degree completion checkbox"
echo "   ✗ Video introduction link (long text)"
echo "   ✗ Prior work link (long text)"
echo ""
echo "=========================================="
echo "Troubleshooting:"
echo "=========================================="
echo ""
echo "If form not detected:"
echo "  - Refresh the page"
echo "  - Wait longer for React to render"
echo "  - Check DevTools Console for errors"
echo "  - Verify extension is loaded (chrome://extensions)"
echo ""
echo "If fields not filling:"
echo "  - Check that profile is set up in extension"
echo "  - Open DevTools Console (F12)"
echo "  - Look for field classification messages"
echo "  - Document which fields were not recognized"
echo ""
echo "=========================================="
echo "See test-ashby-form.md for detailed analysis"
echo "=========================================="

